name: Build applicaiton

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://entel:crazypassword@localhost:5432/enteldb
      POSTGRES_USER: entel
      POSTGRES_PASSWORD: crazypassword
      POSTGRES_DB: enteldb
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install dependencies
        id: install-dependencies
        run: npm i
      - name: Start docker
        id: start-docker
        run: docker-compose up -d
      - name: Migrate database
        id: migrate-database
        run: blitz prisma migrate deploy --preview-feature
      - name: Build application
        id: build-application
        run: blitz build
